### ISSUE TITLE
Add Todo MVC example

### ISSUE THREAD

**Issue by bwhmather** [bwhmather/bdc-js#20]
See https://github.com/tastejs/todomvc/blob/master/app-spec.md for detailed specification.

### No todos
  - [x] When there are no todos, #main and #footer should be hidden.

### New todos
  - [x] New todos are entered in the input at the top of the app.
  - [x] The input element should be focused when the page is loaded, preferably by
  using the autofocus input attribute.
  - [x] Pressing Enter creates the todo, appends it to the todo list, and clears
  the input.
  - [x] Make sure to .trim() the input and then check that it's not empty before
  creating a new todo.

### Mark all as completed
  - [x] The mark all completed checkbox toggles all the todos to the same state as
  itself.
  - [x] The make all completed button should be cleared after the "Clear completed"
  button is clicked.
  - [x] The "Mark all as complete" checkbox should also be updated when single todo
  items are checked/unchecked.

### Item interaction
  - [x] Clicking an item checkbox marks the todo as complete by updating its
  completed value and toggling the class completed on its parent `<li>`
  - [x] Double-clicking an item `<label>` activates editing mode, by toggling the
  .editing class on its `<li>`.
  - [x] Hovering over the todo shows the remove button (`.destroy`)

### Editing
  - [x] When editing mode is activated it will hide the other controls and bring
  forward an input that contains the todo title
  - [x] The item should be focused when editing starts.
  - [x] The edit should be saved on both when the enter key is pressed, and the editing class
  should be removed.
  - [x] The edit should also be saved when focus is lost.
  - [x] Make sure to .trim() the input and then check that it's not empty.
  - [x] If it's empty the todo should instead be destroyed.
  - [x] If escape is pressed during the edit, the edit state should be left and any changes be discarded.

### Counter
  -  [x] Displays the number of active todos in a pluralized form.
  - [x] Make sure the number is wrapped by a `<strong>` tag.
  - [x] Also make sure to pluralize the item word correctly: 0 items, 1 item, 2
  items. Example: 2 items left

### Clear completed button
  - [x] Removes completed todos when clicked.
  - [x] Should be hidden when there are no completed todos.

### Persistence
  - [ ] Your app should dynamically persist the todos to localStorage.
  - [ ] If possible, use the keys id, title, completed for each item.
  - [ ] Make sure to use this format for the localStorage name: todos-[framework].
  - [ ] Editing mode should not be persisted.

### Routing
The following routes should be implemented: 
  - [x] `#/` (all - default)
  - [x] `#/active`
  - [x] `#/completed` (`#!/` is also allowed).
  - [x] When the route changes, the todo list should be filtered on a model level
  and the selected class on the filter links should be toggled.
  - [x] When an item is updated while in a filtered state, it should be updated
  accordingly. E.g. if the filter is Active and the item is checked, it should be hidden.
  - [x] Make sure the active filter is persisted on reload.
